// <auto-generated />
using MailboxAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace MailboxAPI.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20180522224718_MailboxAPI.API.Models.ApplicationContext")]
    partial class MailboxAPIAPIModelsApplicationContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MailboxAPI.Models.Entities.Area", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("name");

                    b.HasKey("id");

                    b.ToTable("tblArea");
                });

            modelBuilder.Entity("MailboxAPI.Models.Entities.Factura", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("Area_id");

                    b.Property<string>("CNPJ");

                    b.Property<string>("EmissionDate");

                    b.Property<string>("NoNote");

                    b.Property<string>("NoteType");

                    b.Property<string>("PO");

                    b.Property<byte[]>("PdfPath");

                    b.Property<string>("TotalValue");

                    b.HasKey("Id");

                    b.HasIndex("Area_id");

                    b.ToTable("tblFacturas");
                });

            modelBuilder.Entity("MailboxAPI.Models.Entities.Factura", b =>
                {
                    b.HasOne("MailboxAPI.Models.Entities.Area", "Area")
                        .WithMany()
                        .HasForeignKey("Area_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
