// <auto-generated />
using MailboxAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace MailboxAPI.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MailboxAPI.Models.Factura", b =>
                {
                    b.Property<long>("FacturaId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Area");

                    b.Property<string>("CNPJ");

                    b.Property<string>("EmissionDate");

                    b.Property<string>("NoNote");

                    b.Property<string>("NoteType");

                    b.Property<string>("PO");

                    b.Property<byte[]>("PdfPath");

                    b.Property<string>("TotalValue");

                    b.HasKey("FacturaId");

                    b.ToTable("Facturas");
                });
#pragma warning restore 612, 618
        }
    }
}
